### PR TITLE
readme: point to head-only depot-tools formula

### PR DESCRIPTION
**Pull request by paulirish**

### CODE REVIEW

**Comment by paulirish** [comment]
@cliffrowley ping

**Comment by cliffrowley** [comment]
Hey @paulirish - this repository is no longer actively maintained (I changed the README recently to reflect this!) - sorry!

**Comment by paulirish** [comment]
Yes exactly. People still end up on your repo. This change just points them to something maintained.

If you don't want to merge this, you should delete your repo instead.

**Comment by cliffrowley** [comment]
Oh, then I misunderstood - apologies.  I shall merge immediately.

**Comment by paulirish** [comment]
Cheers. :)

**Pull request merged**
